doc/en/source/conf.py
doc/en/source/index.rst

Using styled CSS is a *should* TSC requirement

Add FIWARE Processing CSS and Badge to Docs

---

discovery/repository.go

Hi,
This is a part of the fix. Other DB queries still need to be updated though. I will commit more time to it later. For now only fixes for updateEntity were made.
Fixing it for queryEntities will be a bit more annoying because of the statements' complexity.
Although I didn't apply it formulations such as INSERT INTO .... ON CONFLICT (...) DO UPDATE might be applied to get rid of the very repetitive SELECT * FROM .... if rowns.Next() == false .... INSERT else UPDATE sequences.
I just conducted minimal testing so please review this pull request before merging.

Fix Possible SQL Injection

---

doc/tutorial/fogflow.md

Added doc related to fogflow cloud node setup.

updated content for "# Start Up Orion" section

---

doc/en/source/example5.rst

Additional APIs of thin broker added to the user manual.

Additional Registrations APIs of broker in manual

---

broker/restapisrv.go
broker/thinBroker.go
common/ngsi/ngsi.go
common/ngsi/ngsiclient.go

Added southbound feature to fogflow.

Fogflow southbound

---

doc/roadmap.md

FogFlow RoadMap for next one year.

roadmap.md

---

broker/thinBroker.go

Fog flow v1 notification issue

---

doc/en/source/example4.rst
doc/en/source/onepage.rst

Document updated from v2 to v2/op/notify for orion broker in subscription request for NGSIV2.

fix function postNotifyContext issue

---

doc/en/source/integration.rst

FogFlow Manual re-construction: Update Integration heading

update fogflow manual

---

broker/utils.go

solve issue Feature #82

---

application/operator/face-counter/main.py
cli/python/fogflowclient.py
cli/python/test.py
designer/main.js
designer/public/lib/ngsi/ngsiproxy.js
docker/core/http/local/docker-compose.yml
docker/core/http/local/nginx.conf

add a python client that can trigger a service topology programmatically

Feature 81

---

designer/dgraph.js
designer/main.js

solve bug 93

---

doc/en/source/ngsi_ld_api_walkthrough.rst

Please share any review comments.

Added manual for NGSI-LD API support.

---

broker/restapisrv.go
broker/serializer.go
broker/thinBroker.go
broker/utils.go
common/ngsi/ngsi.go
common/ngsi/ngsiclient.go

Updated NGSI-LD feature implementation for map data structure, including other changes.

Feature 76 latest

---

docker/core/http/pep_config.js
docker/edge/http/delete.sh
docker/edge/http/delete_config.js
docker/edge/http/oauth_config.js
docker/edge/http/script.sh
docker/edge/http/start.sh
docker/edge/http/stop.sh

fogflow security code changes

---

broker/thinBroker.go
common/ngsi/ngsiclient.go
discovery/fastDiscovery.go
discovery/main.go

code done for UpdateLDSubscription subscribeContextAbailability in discocery

Feature 76 update temp

---

designer/dgraph.js

fix for bug-113

---

application/template/python/dockerfile
doc/en/source/api.rst

Featuretemp 133

---

doc/en/source/api.rst

change subscription request path

---

application/template/NGSILD/goTemplate/build
application/template/NGSILD/goTemplate/config.json
application/template/NGSILD/goTemplate/dockerfile
application/template/NGSILD/goTemplate/function.go
application/template/NGSILD/goTemplate/main.go
application/template/NGSILD/goTemplate/ngsiclient.go

add go template

---

test/jmeter/ngsi-ld/ngsi-ld-fogflow_updated.jmx

add updated jmeter script

---

application/template/NGSILD/javascript/ngsi/ngsiclient.js
application/template/NGSILD/python/main.py
broker/restapisrv.go
broker/serializer.go
broker/thinBroker.go
broker/utils.go
common/ngsi/ngsi.go

Add two go structure for upsert api

Add two structre for upsert APi

---

application/operator/NGSI-LD-operator/PollutionDemo/build
application/operator/NGSI-LD-operator/PollutionDemo/config.json
application/operator/NGSI-LD-operator/PollutionDemo/dockerfile
application/operator/NGSI-LD-operator/PollutionDemo/function.js
application/operator/NGSI-LD-operator/PollutionDemo/main.js
application/operator/NGSI-LD-operator/PollutionDemo/ngsi/ngsiagent.js
application/operator/NGSI-LD-operator/PollutionDemo/ngsi/ngsiclient.js
application/operator/NGSI-LD-operator/PollutionDemo/package-lock.json
application/operator/NGSI-LD-operator/PollutionDemo/package.json
broker/thinBroker.go
broker/utils.go

edit ngsild link for notification

---

broker/restapisrv.go
doc/en/source/scorpioIntegration.rst
test/UnitTest/NGSI-LD/test_casesNGSI-LD.py

Corrected code for query for entity by type

corrected code for query for entity by type

---

release/3.2/edge/start.sh

Update edge node star.sh script

Update edge node star.sh script

---

application/operator/NGSI-LD-operator/alertForSpeedInNGSILD/build
application/operator/NGSI-LD-operator/alertForSpeedInNGSILD/function.js
broker/thinBroker.go
broker/utils.go
doc/en/source/scorpioIntegration.rst
test/UnitTest/NGSI-LD/ld_data.py
test/UnitTest/NGSI-LD/test_casesNGSI-LD.py

incorporated comment for integration with NGSILD broker

Upsert temp

---

test/jmeter/ngsi-ld/local-NGSILD-updater.jmx

Add jmeter script

---

application/template/NGSILD/javascript/main.js
application/template/NGSILD/python/main.py
application/template/javascript/main.js
application/template/python/main.py

change template to configure kubernates environment vairaible

change template to configure kubernates environment vairaible

---

broker/thinBroker.go

solve #334

---

k8sWorker/Dockerfile
k8sWorker/Dockerfile4Arm
k8sWorker/Dockerfile4Armv8
k8sWorker/README.md
k8sWorker/build
k8sWorker/config.json
k8sWorker/executor.go
k8sWorker/main.go
k8sWorker/pod.go
k8sWorker/startworkers.sh
k8sWorker/stopworkers.sh
k8sWorker/worker.go

incorporated comment

---

application/operator/NGSI-LD-operator/WaterPumpFog/build
application/operator/NGSI-LD-operator/WaterPumpFog/config.json
application/operator/NGSI-LD-operator/WaterPumpFog/dockerfile
application/operator/NGSI-LD-operator/WaterPumpFog/function.js
application/operator/NGSI-LD-operator/WaterPumpFog/main.js
application/operator/NGSI-LD-operator/WaterPumpFog/ngsi/ngsiagent.js
application/operator/NGSI-LD-operator/WaterPumpFog/ngsi/ngsiclient.js
application/operator/NGSI-LD-operator/WaterPumpFog/package-lock.json
application/operator/NGSI-LD-operator/WaterPumpFog/package.json
broker/serializer.go
broker/thinBroker.go
test/UnitTest/NGSI-LD/test_casesNGSI-LD.py
test/UnitTest/NGSI-LD/test_new.py
test/UnitTest/v1/test_casesNGSIv1.py

Add fogfunction for waterpump

---

broker/utils.go

add code to solve problem of performance

Add documentLoader code

---

doc/en/source/setup.rst
doc/en/source/system_monitoring.rst
docker/edge/http/edge_start.sh
docker/edge/http/edge_stop.sh

Manual is updated in accordance to the latest code flow and structure.

Manual Update : For Edge Setup 

---

common/datamodel/datamodel.go
master/taskMgr.go

Solve issue 282 . still need to validate

solve issue 282

---

broker/thinBroker.go
broker/utils.go

Resolve issue related to usecase

Usecase bug

---

test/ldcontext/ngsi-ld-core-context-v1.3.jsonld

added fogflow default ldcontext

---

.github/workflows/main.yml
test/UnitTest/persistance/data.py
test/UnitTest/persistance/test_persistance.py

Persistance_Testcase; New test cases added

---

designer/main.js
designer/public/js/operator.js
designer/public/js/topology.js
designer/rabbitmq.js
docker/core/http/docker-compose-advanced.yml
docker/core/http/docker-compose.yml
master/master.go
release/latest/cloud/docker-compose.yml

resolved designer and rabbitMQ bootup issues.

Merging bug after catalogue feature

---

doc/en/source/k8sIntegration.rst
doc/en/source/k8s_security_rbac.rst

Updated k8s tutorial as required for deployment folder path

---

designer/Dockerfile_development

Added rabbitmq dependency in the designer Dockerfile.

Updated Designer Dockerfile

---

deployment/helm/README.md
deployment/helm/cloud-chart/values.yaml
deployment/helm/edge-chart/values.yaml

Pull request contains below addition:
1. Liveness and readiness probe in values.yml files
2. README file containing information on helm chart fogflow

Readiness and Liveliness Support Addition in FogFlow helm deployment with readme modification

---

designer/public/js/index.js

multi edge issue has been resolved.

resolved issue of  multi edges

---

designer/rabbitmq.js

rabbitMQ URL get from the config file

resolved issue #350

---

broker/serializer.go

resolved issue_357

---

designer/public/js/index.js
designer/public/lib/ngsi/LDngsiclient.js

NGSI-LD device creation and deletion.
Updated V1 format for device creation.

NGSI-LD device creation from UI

---

designer/package.json
test/UnitTest/NGSI-LD/ld_data.py
test/UnitTest/NGSI-LD/test_casesNGSI-LD.py
test/UnitTest/persistance/test_persistance.py

Pull request contains below addition:
- Updated Persistence Test-cases to adapt to new version, so it corrects the failing build.
- Addition of new test cases based on Geo-location, visualization feature and NGSI-LD use cases.

Revised Pull Request for updating CI/CD scripts to adapt recent version 

---

broker/serializer.go

change code for global query

---

designer/public/js/index.js
designer/public/lib/ngsi/LDngsiclient.js

added the feature of device creation based on ngsi-ld
remove unwanted function from the LDngsiclient.js
formated the code of LDngsiclient.js

device create based on ngsi-ld

---

designer/main.js

error handling for DELETE APIs (intent delete and fogfunction delete) in Designer

Resolved issue 380

---

designer/config.json
doc/en/source/onepage.rst
docker/edge/http/edge_start.sh
release.sh
release/3.2.6/cloud/docker-compose.yml
release/3.2.6/edge/docker-compose.yml
release/3.2.6/edge/start.sh
test/migration-test/main.js
test/orchestration-test/main.js
worker/edgecontroller.go
worker/kubernetes.go

make the tutorial consistent

---

designer/config.json
doc/en/source/index.rst
doc/en/source/onepage.rst
doc/en/source/setup.rst
release.sh
release/3.2.8/cloud/config.json
release/3.2.8/cloud/docker-compose.yml
release/3.2.8/edge/config.json
release/3.2.8/edge/docker-compose.yml
release/3.2.8/edge/start.sh
release/3.2.8/edge/stop.sh
worker/dockerengine.go
worker/edgecontroller.go
worker/engine.go
worker/executor.go
worker/kubernetes.go

prepared for the stable version 3.2.8

include the new release scripts
